# For Bundler.with_clean_env
require 'bundler/setup'

PACKAGE_NAME = "gem"
VERSION = "1.0.0"
TRAVELING_RUBY_VERSION = "20251107-3.4.7"
TRAVELING_RUBY_PKG_DATE = TRAVELING_RUBY_VERSION.split("-").first
TRAVELING_RB_VERSION = TRAVELING_RUBY_VERSION.split("-").last
RUBY_COMPAT_VERSION = TRAVELING_RB_VERSION.split(".").first(2).join(".") + ".0"
RUBY_MAJOR_VERSION = TRAVELING_RB_VERSION.split(".").first.to_i
RUBY_MINOR_VERSION = TRAVELING_RB_VERSION.split(".")[1].to_i

# Platform/target definitions
PLATFORMS = [
  { os: :linux,   arch: :x86_64, musl: false },
  { os: :linux,   arch: :arm64,  musl: false },
  { os: :linux,   arch: :x86_64, musl: true  },
  { os: :linux,   arch: :arm64,  musl: true  },
  { os: :macos,   arch: :x86_64, musl: false },
  { os: :macos,   arch: :arm64,  musl: false },
  { os: :windows, arch: :x86_64, musl: false },
  { os: :windows, arch: :arm64,  musl: false },
]

def platform_name(p)
  if p[:os] == :linux && p[:musl]
    "linux-musl-#{p[:arch]}"
  else
    "#{p[:os]}-#{p[:arch]}"
  end
end

def package_task_name(p)
  "package:#{platform_name(p)}"
end

def tarball_name(p)
  "build/traveling-ruby-#{TRAVELING_RUBY_VERSION}-#{platform_name(p)}.tar.gz"
end

# Generate all package tasks and file rules
PLATFORMS.each do |plat|
  desc "Package #{PACKAGE_NAME} for #{platform_name(plat)}"
  task package_task_name(plat) => [ :bundle_install, tarball_name(plat) ] do
    create_package(TRAVELING_RUBY_VERSION, platform_name(plat), plat[:os] == :windows ? :windows : :unix)
  end

  file tarball_name(plat) do
    download_runtime(TRAVELING_RUBY_VERSION, platform_name(plat))
  end
end

# Meta tasks for groups
task "package:windows" => PLATFORMS.select { |p| p[:os] == :windows }.map { |p| package_task_name(p) }
task "package:linux"   => PLATFORMS.select { |p| p[:os] == :linux && !p[:musl] }.map { |p| package_task_name(p) }
task "package:linux:musl" => PLATFORMS.select { |p| p[:os] == :linux && p[:musl] }.map { |p| package_task_name(p) }
task "package:linux:glibc" => PLATFORMS.select { |p| p[:os] == :linux && !p[:musl] }.map { |p| package_task_name(p) }
task "package:macos"   => PLATFORMS.select { |p| p[:os] == :macos }.map { |p| package_task_name(p) }

desc "Package #{PACKAGE_NAME} for all platforms"
task :package => PLATFORMS.map { |p| package_task_name(p) }

desc "Install gems to local directory. Usage: rake package:bundle_install[platform] (e.g. linux, windows, macos)"
task :bundle_install do
  if RUBY_VERSION !~ /^#{RUBY_MAJOR_VERSION}\.#{RUBY_MINOR_VERSION}\./
    abort "You can only 'bundle install' using Ruby #{TRAVELING_RB_VERSION}, because that's what Traveling Ruby uses. \n You are using Ruby #{RUBY_VERSION}."
  end
  sh "rm -rf build/tmp"
  sh "mkdir -p build/tmp"
  sh "cp packaging/Gemfile packaging/Gemfile.lock build/tmp/"
  Bundler.with_unbundled_env do
    sh "cd build/tmp && env bundle config set --local path '../vendor' && env BUNDLE_DEPLOYMENT=true bundle install --verbose"
  end
  sh "rm -rf build/tmp"
  sh "rm -rf build/vendor/*/*/cache/*"
  sh "rm -rf build/vendor/ruby/*/extensions" # remove host built extensions
end



def create_package(version, target, os_type)
  package_dir = "pkg/#{PACKAGE_NAME}-#{VERSION}-#{target}"
  sh "rm -rf #{package_dir}"
  sh "mkdir -p #{package_dir}"
  sh "mkdir -p #{package_dir}/lib/app"
  sh "cp #{PACKAGE_NAME}.rb #{package_dir}/lib/app/"
  sh "mkdir -p #{package_dir}/lib/ruby"
  sh "tar -xzf build/traveling-ruby-#{TRAVELING_RUBY_VERSION}-#{target}.tar.gz -C #{package_dir}/lib/ruby"
  if os_type == :windows
    sh "cp packaging/wrapper.bat #{package_dir}/#{PACKAGE_NAME}.bat"
  else
    sh "cp packaging/wrapper.sh #{package_dir}/#{PACKAGE_NAME}"
  end
  sh "cp -pR build/vendor #{package_dir}/lib/"
  sh "cp packaging/Gemfile packaging/Gemfile.lock #{package_dir}/lib/vendor/"
  sh "mkdir #{package_dir}/lib/vendor/.bundle"
  sh "cp packaging/bundler-config #{package_dir}/lib/vendor/.bundle/config"
  if !ENV['DIR_ONLY']
    sh "tar -czf #{package_dir}.tar.gz #{package_dir}"
    sh "rm -rf #{package_dir}"
  end
end

def download_runtime(version, target)
  sh "cd build && curl -L -O --fail " +
     "https://github.com/trubygems/traveling-ruby/releases/download/rel-#{TRAVELING_RUBY_PKG_DATE}/traveling-ruby-#{version}-#{target}.tar.gz"
end
